version: "3.7"
services:
  sql-server:
    # image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    build: .
    ports:
      - "1433:1433"
    volumes:
      - "db-data:/var/opt/mssql"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass1234
      MSSQL_PID: Express
volumes:
  db-data:
